name: Updated

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 8 * * 1-5'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
        password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: fjuniorr/{% raw %}${{ github.event.repository.name }}{% endraw %}:latest
        cache-from: type=registry,ref=fjuniorr/{% raw %}${{ github.event.repository.name }}{% endraw %}:latest
        cache-to: type=inline
    - name: ETL pipeline
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      run: docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --mount type=bind,source=${PWD},target=/project fjuniorr/{% raw %}${{ github.event.repository.name }}{% endraw %} make all && make notify
    - name: Publish data package
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        make publish
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        RUNID: {% raw %}${{ github.run_id }}{% endraw %}
      with:
        filename: .github/workflow-failure.md
